name: Build and Push Docker Image

on:
  push:
    branches: [ "prod" ] 
    paths-ignore:
      - '**.md'

env:
  DOCKER_IMAGE: "adiqtpi/thestral"
  CONFIG_REPO_NAME: "adi-QTPi/rubie-homelab" 
  CONFIG_FILE_PATH: "docker/services/thestral/docker-compose.yaml"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:v${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-manifest:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homelab Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CONFIG_REPO_NAME }}
          token: ${{ secrets.GIT_PAT }} # Special token to access the other repo

      - name: Update Image
        run: |
          # Looks for "image: something:..." and replaces it with the new version
          sed -i 's|image: ${{ env.DOCKER_IMAGE }}:.*|image: ${{ env.DOCKER_IMAGE }}:v${{ github.run_number }}|' ${{ env.CONFIG_FILE_PATH }}
          
          git config user.name "Rubie"
          git config user.email "rubie@github.com"
          git commit -am "[thestral] bump docker image to v${{ github.run_number }}"
          git push